camera:
  voltage_threshold: 0.5
  S: 8
  frame_height: 720
  frame_width: 1280
  pixel_bit_depth: 12
  nbhd_size:
  - 2  # nbhd_height
  - 2  # nbhd_width
  scheme:  # A matrix (saved as a list) with the shape of (S, nbhd_height, nbhd_width) 
  - - - 1
      - 0
    - - 0
      - 0
  - - - 1
      - 0
    - - 0
      - 0
  - - - 0
      - 1
    - - 0
      - 0
  - - - 0
      - 1
    - - 0
      - 0
  - - - 0
      - 0
    - - 1
      - 0
  - - - 0
      - 0
    - - 1
      - 0
  - - - 0
      - 0
    - - 0
      - 1
  - - - 0
      - 0
    - - 0
      - 1 
  save_output: true
  save_dir: result/

data:
  type: 'img_seq'  # 'img_seq' or 'video' or 'img'
  path: 'videos/airboard_1/airboard_1/240/airboard_1'
  extension: 'jpg'
